name: Dump and Restore | pg-import

on:
  workflow_dispatch:

jobs:
  dump-and-restore:
    runs-on: ubuntu-latest

    env:
      PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
      SSL_CERT_BASE64: ${{ secrets.SSL_CERT_BASE64 }}

    steps:
      - name: Decode SSL Cert
        run: |
          echo "${{ secrets.SSL_CERT_BASE64 }}" | base64 --decode > us-east-1-bundle.pem

      - name: Dump and restore using pg-import
        run: |
          npx @neondatabase/pg-import@latest \
            --silent false \
            --accept-all false \
            --backup-file-path ${{ github.workspace }}/backup.bk \
            --source="${{ env.PROD_DATABASE_URL }}" \
            --destination="${{ env.DEV_DATABASE_URL }}"
