name: Backup and Restore PostgreSQL

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight ET (us-east-1)
  workflow_dispatch:

jobs:
  db-backup-and-restore:
    runs-on: ubuntu-latest

    env:
      PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }} # Production or primary database
      DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }} # Development database
      PG_VERSION: '16'

    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql-common
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Get timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +%d-%B-%Y@%H:%M:%S)" >> $GITHUB_ENV

      - name: Run pg_dump to create a backup
        run: |
          TIMESTAMP="${{ env.TIMESTAMP }}"
          /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/pg_dump ${{ env.PROD_DATABASE_URL }} -F c -f "${TIMESTAMP}.dump"

      - name: Restore database to development
        run: |
          TIMESTAMP="${{ env.TIMESTAMP }}"
          /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/pg_restore -U postgres -d ${{ env.DEV_DATABASE_URL }} -c "${TIMESTAMP}.dump"

  post-to-slack-webhook:
    runs-on: ubuntu-latest
    needs: db-backup-and-restore # This ensures this job runs after db-backup-and-restore

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run the JavaScript script
        run: node src/index.js
