name: Test failure / success handling

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  do-something:
    runs-on: ubuntu-latest

    env:
      A: 1
      B: 2 # force failure/success: !=1 for failure, 1 for success

    steps:
      - name: A/B Check
        if: ${{ env.A != env.B }}
        run: exit 1

  handle-failure:
    runs-on: ubuntu-latest
    needs: do-something
    if: ${{ failure() }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the JavaScript script
        run: |
          node src/failure.js

  handle-success:
    runs-on: ubuntu-latest
    needs: do-something
    if: ${{ success() }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the JavaScript script
        run: |
          node src/success.js
